// <auto-generated />
using Cuchillos2023.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cuchillos2023.DataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231030200755_CreateCategoriasTableToDb")]
    partial class CreateCategoriasTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cuchillos2023.Models.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCategoria")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            NombreCategoria = "Filetero"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 3,
                            NombreCategoria = "Trinchero"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            NombreCategoria = "Puntillero"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            NombreCategoria = "Chuletero"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            NombreCategoria = "Cocinero"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
